url: 'https://halikowski.github.io/' # your main domain
baseurl: 'Portfolio/'
theme: jekyll-theme-minimal
title: Mateusz Halikowski - Portfolio
description: Welcome to my portfolio page! Here You can see my recent works in the Data Engineering field. Learning new stuff day by day.
logo: https://media.licdn.com/dms/image/D4D03AQFxVvZaTxqxNg/profile-displayphoto-shrink_200_200/0/1709024330126?e=1725494400&v=beta&t=mQsqnigkEAgtp8kKlqL6a172YdcSrNtl9Zujctkmyes
google_analytics: G-5V4FYF672X
show_downloads: false
